version: "3"
services:
  mysql-database:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exonmobile
    platform: linux/x86_64

volumes:
  dbdata:

